version: "3"

services:
  app:
    container_name: bshp_v3
    image: dark_h14/bshp_v3:latest
    environment:
      - DB_HOST=db
      - DB_PORT=27017
      - TEST_MODE=true
      - DEBUG=true
      - DB_URL=mongodb://db:27017
      - DATASET_BATCH_LENGTH=200000
      - QUANTIZE=true        
    build:
        context: ./bshp_ml
        dockerfile: Dockerfile   
    ports:
      - "8061:8061"
      - "5678:5678"
    volumes:
      - ./bshp_ml/app:/app
      - ./models:/models
    networks:
      - custom
    depends_on:
      - db
    restart: unless-stopped      
    entrypoint: 
      - "sh"
      - "-c"
      - |
        pip install debugpy -t /tmp \
        && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 \
        -m uvicorn main_app:app --host 0.0.0.0 --port 8061 --reload
  db:

    image: mongo:6.0.21
    container_name: bshp_db 
    ports:
      - "27117:27017"
    volumes:
      - ./db/data:/data/db
    networks:
      - custom

networks:
  custom:
    driver: bridge
