FROM python:3.12.4
 
LABEL authors="dark_h14"

WORKDIR /app
COPY ./bshp_ml/requirements.txt .
EXPOSE 8061
RUN python3 -m pip install --root-user-action=ignore --upgrade pip && python3 -m  pip install --root-user-action=ignore -r requirements.txt

ENV PYTHONPATH=/app

COPY ./bshp_ml/app .
COPY ./models /_models
COPY ./bshp_ml/start.sh /app/start.sh
RUN chmod +x /app/start.sh

ENTRYPOINT [ "/app/start.sh" ]
CMD ["uvicorn", "main_app:app", "--host", "0.0.0.0", "--port", "8061"]